version: '3.4'

services:
  catalogdb:
    image: mongo

  rabbitmq:
    image: rabbitmq:3-management-alpine

  
  catalog.api:
    image: ${DOCKER_REGISTRY-}catalogapi
    build:
      context: .
      dockerfile: Services/Catalog/Catalog.API/Dockerfile
  
  ocelotapigw:
    image: ${DOCKER_REGISTRY-}ocelotapigw
    build:
      context: .
      dockerfile: ApiGateways/OcelotApiGw/Dockerfile  

  email.api:
    image: ${DOCKER_REGISTRY-}emailapi
    build:
      context: .
      dockerfile: Services/Email/Email.API/Dockerfile

volumes:
  mongo_data:
 

